name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build React app
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.6.0
        with:
          args: --delete
          source_dir: ./frontend/build
          bucket: ${{ secrets.FRONTEND_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-backend:
    name: Deploy Backend to EB
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Zip backend for EB
        working-directory: ./backend
        run: zip -r backend.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: ${{ secrets.BACKEND_EB_APP }}
          environment_name: ${{ secrets.BACKEND_EB_ENV }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          bucket_name: ${{ secrets.BACKEND_EB_BUCKET }}
          bucket_key: backend-${{ github.sha }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
